### ISSUE TITLE
Enable failing tests

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-distribution#1242]
**Description:**
Following lang BBEs are disabled at building:

- [ ] "ballerina-to-openapi",
- [x] "xa-transactions",
- [x]  "retry-transactions",
- [x] "non-transaction-retry",
- [x] "local-transactions-with-handlers",
- [x] "local-transactions",
- [ ] "log-api",
- [ ] "optional-type",
- [ ] "while",
- [x] "function-pointers",
- [x] "modules"

These should be enabled after fixing them.

Also the `CentralTests` tests class is disabled.

`org.ballerina.devtools.central.CentralTest`

**Comment by MaryamZi** [comment]
The following BBEs were fixed in https://github.com/ballerina-platform/ballerina-distribution/pull/1246 and are enabled.

* "function-pointers"
* "modules"

https://github.com/ballerina-platform/ballerina-lang/issues/28136 needs to be fixed to enable the tests for the following BBEs. The compilation errors in the test files of these BBEs have been fixed in https://github.com/ballerina-platform/ballerina-distribution/pull/1246.

* "optional-type"
* "while"

**Comment by MaryamZi** [comment]
The transaction BBE tests were fixed and enabled in #1251.
* "xa-transactions"
* "retry-transactions"
* "non-transaction-retry"
* "local-transactions-with-handlers"
* "local-transactions"

**Comment by ThisaruGuruge** [comment]
> The transaction BBE tests were fixed and enabled in #1251.
> 
> * "xa-transactions"
> * "retry-transactions"
> * "non-transaction-retry"
> * "local-transactions-with-handlers"
> * "local-transactions"

Updated the issue

**Comment by ThisaruGuruge** [comment]
Completed
