### ISSUE TITLE
Content issues in ballerina help

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#251]
**Description:**

1. Descriptions of some commands are ended with full stop but some are not.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/16300038/70422864-704f1600-1a92-11ea-856e-49794ef2b74f.png">

2. Should we list "Update Tool Commands" before the "Other Commands"?

3. Need to rename "Update tool Commands" to "Update Tool Commands" ?

<img width="475" alt="image" src="https://user-images.githubusercontent.com/16300038/70423034-c623be00-1a92-11ea-93a9-ef32e5d0ee91.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
1. openapi is loading from the jballerina distribution. So this cannot be fixed from distrbution
2. There is no way to change the order as "Other Commands" as its loaded from jballerina distribution itself.
3. This is fixed in following commit
https://github.com/ballerina-platform/ballerina-distribution/pull/286/commits/867197c0a80956b2c8ce32b0c70511a328746050
