### ISSUE TITLE
`dist list` removes a distribution from the remotes list once it's downloaded

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#274]
This is the output given before downloading the 1.0.4 version.
```
$ ballerina dist list
Distributions available locally: 

  jballerina-1.1.0-alpha

Distributions available remotely: 

  jballerina-1.0.0
  jballerina-1.0.1
  jballerina-1.0.2
  jballerina-1.0.3
  jballerina-1.0.4
```
And this is the output I get after I downloaded 1.0.4.
```
$ ballerina dist list
Distributions available locally: 

* jballerina-1.0.4
  jballerina-1.1.0-alpha

Distributions available remotely: 

  jballerina-1.0.0
  jballerina-1.0.1
  jballerina-1.0.2
  jballerina-1.0.3
```
Notice how 1.0.4 (and 1.1.0-alpha too for that matter, in both lists) is missing in this list. Is this intentional? Isn't the idea of displaying the remote versions to list all the versions available remotely? Wouldn't this send the wrong idea that 1.0.4 and 1.1.0-alpha is not available remotely?

**Comment by keizer619** [comment]
1. Actually `jballerina-1.1.0-alpha` is not in the remote as its a pre release. Currently we are not including pre releases in the remote section. 

2. Yes it was intentional if you pull/update to any versions from the remote those will be not included remote section as these are in the local list. If its confusing we can change the title something like `Distributions available remotely to download`
