### ISSUE TITLE
Standard library integration tests are not working properly in the distribution build

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-distribution#4625]
**Description:**
> $subject

When running the distribution build, standard library integration tests are not running properly. Tested with following integration test [1] which is written for OpenAPI definition generation for HTTP service, this test passed even though it should fail according to recent compiler plugin changes.

[1] - https://github.com/ballerina-platform/ballerina-distribution/blob/master/stdlib-integration-tests/http/tests/rest_introspection_test.bal

**Comment by dsplayerX** [comment]
This issue was fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/5259. Tests `testRestApiDoc` and `testIntrospectionResourceAvailability` were disabled in the same PR (commit:https://github.com/ballerina-platform/ballerina-distribution/pull/5259/commits/b1cd993863f82cbd01f194f905fc7a07e359bff8).

Created new issue https://github.com/ballerina-platform/ballerina-distribution/issues/5272 to keep track of fixing and re-enabling these disabled tests.
