### ISSUE TITLE
Upgrade org.quartz-scheduler:quartz version to resolve CVE-2023-39017

### ISSUE THREAD

**Issue by nadheesh** [ballerina-platform/ballerina-distribution#4858]
**Description:**
A critical vulnerability (CVE-2023-39017) with `org.quartz-scheduler:quartz` is found. Need to upgrade the version at least to `2.4.0-rc1`.

**Comment by kalaiyarasiganeshalingam** [comment]
We are using 2.3.2. Quartz's next major or minor version libs haven't been released yet. Updated versions are in RC, and we can't go with the RC pack. This issue is not fixed yet. So, we add this vulnerability to the ignore list in the distribution.
Please check this to get more info: 
https://github.com/ballerina-platform/module-ballerina-task/pull/489#issuecomment-1700364395
